#!/bin/bash
{
  rm -rf chrome/ firefox/ github-jira-link-firefox.0.1.zip github-jira-link-chrome.0.1.zip

  mkdir firefox
  cp contentScript.js icon_128.png manifest.json options.css options.html options.js styles.css README_firefox.md firefox/
  zip -r github-jira-link-firefox.0.1.zip firefox

  mkdir chrome
  cp contentScript.js icon_128.png options.css options.html options.js styles.css README_chrome.md chrome/
  sed '21,28d' firefox/manifest.json | tee -a chrome/manifest.json
  echo "  }" >> chrome/manifest.json
  echo "}" >> chrome/manifest.json
  echo "" >> chrome/manifest.json
  zip -r github-jira-link-chrome.0.1.zip chrome
} >& /dev/null
echo "🎉 Chrome release created in ./chrome/"
echo "🎉 Firefox release created in ./firefox/"
